const codeLangMap = {
  "js": "JavaScript",
  "py": "Python",
  "rb": "Ruby",
  "cpp": "C++",
  "java": "Java",
  "c": "C",
  "cs": "C#",
  "go": "Go",
  "kt": "Kotlin",
  "lua": "Lua",
  "php": "PHP",
  "swift": "Swift",
  "ts": "TypeScript",
  "scala": "Scala",
  "rust": "Rust",
  "dart": "Dart",
  "perl": "Perl",
  "r": "R",
  "haskell": "Haskell",
  "elixir": "Elixir",
  "erlang": "Erlang",
  "groovy": "Groovy",
  "julia": "Julia",
  "matlab": "MATLAB",
  "objectivec": "Objective-C",
  "powershell": "PowerShell",
  "shell": "Shell",
  "sql": "SQL",
  "visualbasic": "Visual Basic",
  "kotlin": "Kotlin",
  "typescript": "TypeScript",
  "bash": "Bash",
  "html": "HTML",
  "css": "CSS",
  "sass": "Sass",
  "less": "Less",
  "c++": "C++",
  "c#": "C#",
  "javascript": "JavaScript",
  "python": "Python",
  "ruby": "Ruby",
  "visual basic": "Visual Basic",
  "abap": "ABAP",
  "ada": "Ada",
  "apex": "Apex",
  "cobol": "COBOL",
  "delphi": "Delphi",
  "fortran": "FORTRAN",
  "lisp": "Lisp",
  "objective-c": "Objective-C",
  "ocaml": "OCaml",
  "pascal": "Pascal",
  "prolog": "Prolog",
  "racket": "Racket",
  "smalltalk": "Smalltalk",
  "tcl": "Tcl",
  "verilog": "Verilog",
  "vhdl": "VHDL",
  "xml": "XML",
  "agda": "Agda",
  "algol": "ALGOL",
  "apl": "APL",
  "arduino": "Arduino",
  "asp": "ASP",
  "awk": "AWK",
  "basic": "BASIC",
  "bcpl": "BCPL",
  "bourne shell": "Bourne Shell",
  "brainfuck": "Brainfuck",
  "c shell": "C Shell",
  "coldfusion": "ColdFusion",
  "comal": "COMAL",
  "common lisp": "Common Lisp",
  "crystal": "Crystal",
  "d": "D",
  "eiffel": "Eiffel",
  "elm": "Elm",
  "factor": "Factor",
  "forth": "Forth",
  "f#": "F#",
  "gambas": "Gambas",
  "gdscript": "GDScript",
  "gnuplot": "Gnuplot",
  "hyperTalk": "HyperTalk",
  "icon": "Icon",
  "inform": "Inform",
  "io": "Io",
  "j": "J",
  "ksh": "KSH",
  "labview": "LabVIEW",
  "ladder logic": "Ladder Logic",
  "logo": "Logo",
  "m4": "M4",
  "maple": "Maple",
  "mips assembly": "MIPS Assembly",
  "modula-2": "Modula-2",
  "ms sql": "MS SQL",
  "nemerle": "Nemerle",
  "nim": "Nim",
  "opencl": "OpenCL",
  "perl 6": "Perl 6",
  "postscript": "PostScript",
  "powerbuilder": "PowerBuilder",
  "purebasic": "PureBasic",
  "qbasic": "QBasic",
  "rexx": "REXX",
  "ring": "Ring",
  "ruby on rails": "Ruby on Rails",
  "sas": "SAS",
  "scheme": "Scheme",
  "scratch": "Scratch",
  "sed": "sed",
  "solidity": "Solidity",
  "sql server": "SQL Server",
  "standard ml": "Standard ML",
  "thinbasic": "thinBasic",
  "turing": "Turing",
  "vala": "Vala",
  "vbscript": "VBScript",
  "vim script": "Vim Script",
  "webassembly": "WebAssembly",
  "whitespace": "Whitespace",
  "xbase": "xBase",
  "xquery": "XQuery",
  "yacc": "YACC",
  "z shell": "Z Shell",
  "sh": "Shell",
  "zsh": "Zsh",
  "objc": "Objective-C",
  "fallback": ""
};

export default function convertCodeLang(lang: string) {
  return codeLangMap[lang.toLowerCase()] === undefined ? 
    lang.toUpperCase() : codeLangMap[lang];
}